import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "HIGHLIGHTS";

export const actions = addPrefix(ACTION_PREFIX, {
  // GET_TOP_ISSUES_DATA: "GET_TOP_ISSUES_DATA",
  // SET_TOP_ISSUES_DATA: "SET_TOP_ISSUES_DATA",
  // GET_PERFORMANCE_DATA: "GET_PERFORMANCE_DATA",
  // SET_PERFORMANCE_DATA: "SET_PERFORMANCE_DATA"
});
