import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "INSTALLATION_WIZARD";

export const actions = addPrefix(ACTION_PREFIX, {
  INITIALIZE: "INITIALIZE",
  CLOSE: "CLOSE",
  FINISH: "FINISH",
  // CHECK_CONNECTION: "CHECK_CONNECTION",
  // SET_CONNECTION_CHECK_RESULT: "SET_CONNECTION_CHECK_RESULT",
  // SET_OBSERVABILITY: "SET_OBSERVABILITY",
  INSTALL_DIGMA_ENGINE: "INSTALL_DIGMA_ENGINE",
  UNINSTALL_DIGMA_ENGINE: "UNINSTALL_DIGMA_ENGINE",
  START_DIGMA_ENGINE: "START_DIGMA_ENGINE",
  STOP_DIGMA_ENGINE: "STOP_DIGMA_ENGINE",
  SET_INSTALL_DIGMA_ENGINE_RESULT: "SET_INSTALL_DIGMA_ENGINE_RESULT",
  SET_UNINSTALL_DIGMA_ENGINE_RESULT: "SET_UNINSTALL_DIGMA_ENGINE_RESULT",
  SET_START_DIGMA_ENGINE_RESULT: "SET_START_DIGMA_ENGINE_RESULT",
  SET_STOP_DIGMA_ENGINE_RESULT: "SET_STOP_DIGMA_ENGINE_RESULT"
});
