import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "ERRORS";

export const actions = addPrefix(ACTION_PREFIX, {
  GET_ERRORS_DATA: "GET_ERRORS_DATA_ERRORS",
  SET_ERRORS_DATA: "SET_ERRORS_DATA_ERRORS",
  GET_ERROR_DETAILS: "GET_ERROR_DETAILS",
  SET_ERROR_DETAILS: "SET_ERROR_DETAILS",
  GO_TO_TRACE: "GO_TO_TRACE",
  OPEN_RAW_ERROR_STACK_TRACE_IN_EDITOR: "OPEN_RAW_ERROR_STACK_TRACE_IN_EDITOR",
  GO_TO_CODE_LOCATION: "GO_TO_CODE_LOCATION",
  GET_FILES_URIS: "GET_FILES_URIS",
  SET_FILES_URIS: "SET_FILES_URIS"
});
