import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "ERRORS";

export const actions = addPrefix(ACTION_PREFIX, {
  GO_TO_TRACE: "GO_TO_TRACE",
  OPEN_RAW_ERROR_STACK_TRACE_IN_EDITOR: "OPEN_RAW_ERROR_STACK_TRACE_IN_EDITOR",
  GO_TO_CODE_LOCATION: "GO_TO_CODE_LOCATION",
  GET_FILES_URIS: "GET_FILES_URIS",
  SET_FILES_URIS: "SET_FILES_URIS"
});
