import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "MAIN";

export const actions = addPrefix(ACTION_PREFIX, {
  INITIALIZE: "INITIALIZE",
  SET_VIEWS: "SET_VIEWS",
  GET_HIGHLIGHTS_TOP_ISSUES_DATA: "GET_HIGHLIGHTS_TOP_ISSUES_DATA",
  SET_HIGHLIGHTS_TOP_ISSUES_DATA: "SET_HIGHLIGHTS_TOP_ISSUES_DATA",
  LOGIN_RESULT: "LOGIN_RESULT",
  LOGIN: "LOGIN",
  REGISTER_RESULT: "REGISTER_RESULT"
});
