import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "RECENT_ACTIVITY";

export const actions = addPrefix(ACTION_PREFIX, {
  INITIALIZE: "INITIALIZE",
  SET_LIVE_DATA: "SET_LIVE_DATA",
  GO_TO_TRACE: "GO_TO_TRACE",
  CLOSE_LIVE_VIEW: "CLOSE_LIVE_VIEW",
  ADD_ENVIRONMENT_TO_RUN_CONFIG: "ADD_ENVIRONMENT_TO_RUN_CONFIG",
  ADD_ENVIRONMENT_TO_RUN_CONFIG_RESULT: "ADD_ENVIRONMENT_TO_RUN_CONFIG_RESULT",
  CLEAR_RUN_CONFIG: "CLEAR_RUN_CONFIG",
  REGISTER: "REGISTER",
  CHECK_REMOTE_ENVIRONMENT_CONNECTION: "CHECK_REMOTE_ENVIRONMENT_CONNECTION", // deprecated
  APPLY_REMOTE_ENVIRONMENT_SETTINGS: "APPLY_REMOTE_ENVIRONMENT_SETTINGS", // deprecated
  SET_REMOTE_ENVIRONMENT_CONNECTION_CHECK_RESULT:
    "SET_REMOTE_ENVIRONMENT_CONNECTION_CHECK_RESULT", // deprecated
  GET_DIGMATHON_PROGRESS_DATA: "GET_DIGMATHON_PROGRESS_DATA",
  SET_DIGMATHON_PROGRESS_DATA: "SET_DIGMATHON_PROGRESS_DATA",
  OPEN_REGISTRATION_DIALOG: "OPEN_REGISTRATION_DIALOG",
  UPDATE_DIGMATHON_PROGRESS_DATA: "UPDATE_DIGMATHON_PROGRESS_DATA"
});
