import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "INSIGHTS";

export const actions = addPrefix(ACTION_PREFIX, {
  GO_TO_ERRORS: "GO_TO_ERRORS", // deprecated
  GO_TO_ERROR: "GO_TO_ERROR", // deprecated
  GO_TO_TRACE: "GO_TO_TRACE",
  OPEN_HISTOGRAM: "OPEN_HISTOGRAM",
  OPEN_LIVE_VIEW: "OPEN_LIVE_VIEW",
  RECALCULATE: "RECALCULATE",
  SET_RECALCULATED: "SET_RECALCULATED",
  AUTOFIX_MISSING_DEPENDENCY: "AUTOFIX_MISSING_DEPENDENCY", // deprecated
  ADD_ANNOTATION: "ADD_ANNOTATION", // deprecated
  REFRESH_ALL: "REFRESH_ALL", // deprecated
  MARK_INSIGHT_TYPES_AS_VIEWED: "MARK_INSIGHT_TYPES_AS_VIEWED",
  GET_CODE_LOCATIONS: "GET_CODE_LOCATIONS",
  SET_CODE_LOCATIONS: "SET_CODE_LOCATIONS",
  GET_COMMIT_INFO: "GET_COMMIT_INFO",
  SET_COMMIT_INFO: "SET_COMMIT_INFO",
  DISMISS: "DISMISS", // TODO: move to useDismissal
  UNDISMISS: "UNDISMISS", // TODO: move to useDismissal
  MARK_AS_READ: "MARK_AS_READ",
  SET_MARK_AS_READ_RESPONSE: "SET_MARK_AS_READ_RESPONSE",
  MARK_ALL_AS_READ: "MARK_ALL_AS_READ",
  SET_MARK_ALL_AS_READ_RESPONSE: "SET_MARK_ALL_AS_READ_RESPONSE"
});
