import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "INSIGHTS";

export const actions = addPrefix(ACTION_PREFIX, {
  GET_DATA: "GET_DATA",
  SET_DATA: "SET_DATA",
  GO_TO_ERRORS: "GO_TO_ERRORS",
  GO_TO_ERROR: "GO_TO_ERROR",
  GO_TO_METHOD: "GO_TO_METHOD",
  GO_TO_TRACE: "GO_TO_TRACE",
  GO_TO_TRACE_COMPARISON: "GO_TO_TRACE_COMPARISON",
  GO_TO_ASSET: "GO_TO_ASSET",
  OPEN_HISTOGRAM: "OPEN_HISTOGRAM",
  OPEN_LIVE_VIEW: "OPEN_LIVE_VIEW",
  RECALCULATE: "RECALCULATE",
  AUTOFIX_MISSING_DEPENDENCY: "AUTOFIX_MISSING_DEPENDENCY",
  ADD_ANNOTATION: "ADD_ANNOTATION",
  REFRESH_ALL: "REFRESH_ALL",
  MARK_INSIGHT_TYPES_AS_VIEWED: "MARK_INSIGHT_TYPES_AS_VIEWED",
  GET_CODE_LOCATIONS: "GET_CODE_LOCATIONS",
  SET_CODE_LOCATIONS: "SET_CODE_LOCATIONS",
  GET_SPAN_INSIGHT: "GET_SPAN_INSIGHT",
  SET_SPAN_INSIGHT: "SET_SPAN_INSIGHT",
  GET_COMMIT_INFO: "GET_COMMIT_INFO",
  SET_COMMIT_INFO: "SET_COMMIT_INFO",
  LINK_TICKET: "LINK_TICKET",
  UNLINK_TICKET: "UNLINK_TICKET",
  SET_TICKET_LINK: "SET_TICKET_LINK",
  SET_DATA_LIST: "SET_DATA_LIST",
  GET_DATA_LIST: "GET_DATA_LIST",
  DISMISS: "DISMISS",
  UNDISMISS: "UNDISMISS",
  SET_DISMISS_RESPONSE: "SET_DISMISS_RESPONSE",
  SET_UNDISMISS_RESPONSE: "SET_UNDISMISS_RESPONSE"
});
