import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "DASHBOARD";

export const actions = addPrefix(ACTION_PREFIX, {
  INITIALIZE: "INITIALIZE",
  GET_DATA: "GET_DATA",
  SET_DATA: "SET_DATA",
  GET_ENVIRONMENT_INFO: "GET_ENVIRONMENT_INFO",
  SET_ENVIRONMENT_INFO: "SET_ENVIRONMENT_INFO",
  GET_SERVICES: "GET_SERVICES",
  SET_SERVICES: "SET_SERVICES",
  GET_REPORT_ISSUES_STATS: "GET_REPORT_ISSUES_STATS",
  SET_REPORT_ISSUES_STATS: "SET_REPORT_ISSUES_STATS",
  GET_REPORT_ASSETS_STATS: "GET_REPORT_ASSETS_STATS",
  SET_REPORT_ASSETS_STATS: "SET_REPORT_ASSETS_STATS",
  GET_METRICS_REPORT_DATA: "GET_METRICS_REPORT_DATA",
  SET_METRICS_REPORT_DATA: "SET_METRICS_REPORT_DATA",
  GET_SERVICE_ENDPOINTS_DATA: "GET_SERVICE_ENDPOINTS",
  SET_SERVICE_ENDPOINTS_DATA: "SET_SERVICE_ENDPOINTS",
  GET_ENDPOINTS_ISSUES: "GET_ENDPOINTS_ISSUES",
  SET_ENDPOINTS_ISSUES: "SET_ENDPOINTS_ISSUES",
  GET_SERVICE_ENVIRONMENTS: "GET_SERVICE_ENVIRONMENTS",
  SET_SERVICE_ENVIRONMENTS: "SET_SERVICE_ENVIRONMENTS"
});
