import { addPrefix } from "../../utils/addPrefix";

const ACTION_PREFIX = "ASSETS";

export const actions = addPrefix(ACTION_PREFIX, {
  GET_DATA: "GET_DATA",
  SET_DATA: "SET_DATA",
  GET_CATEGORIES_DATA: "GET_CATEGORIES_DATA",
  SET_CATEGORIES_DATA: "SET_CATEGORIES_DATA",
  GET_ASSET_FILTERS_DATA: "GET_ASSET_FILTERS_DATA",
  SET_ASSET_FILTERS_DATA: "SET_ASSET_FILTERS_DATA"
});
