import { addPrefix } from "./utils/addPrefix";

const ACTION_PREFIX = "GLOBAL";

export const actions = addPrefix(ACTION_PREFIX, {
  SET_THEME: "SET_THEME",
  SET_MAIN_FONT: "SET_MAIN_FONT",
  SET_CODE_FONT: "SET_CODE_FONT",
  SET_IS_JAEGER_ENABLED: "SET_IS_JAEGER_ENABLED",
  SET_IS_DIGMA_ENGINE_INSTALLED: "SET_IS_DIGMA_ENGINE_INSTALLED",
  SET_IS_DIGMA_ENGINE_RUNNING: "SET_IS_DIGMA_ENGINE_RUNNING",
  SET_DIGMA_STATUS: "SET_DIGMA_STATUS",
  SET_IS_DOCKER_INSTALLED: "SET_IS_DOCKER_INSTALLED",
  SET_IS_DOCKER_COMPOSE_INSTALLED: "SET_IS_DOCKER_COMPOSE_INSTALLED",
  OPEN_URL_IN_DEFAULT_BROWSER: "OPEN_URL_IN_DEFAULT_BROWSER",
  OPEN_URL_IN_EDITOR_TAB: "OPEN_URL_IN_EDITOR_TAB",
  SEND_TRACKING_EVENT: "SEND_TRACKING_EVENT",
  OPEN_TROUBLESHOOTING_GUIDE: "OPEN_TROUBLESHOOTING_GUIDE",
  OPEN_DOCUMENTATION: "OPEN_DOCUMENTATION"
});
