name: Lint & test & build

on:
  push:
    branches: ["main"]
    # Github Actions don't support YAML anchors yet, so we have to repeat
    # the paths-ignore in both push and pull_request events.
    # More info: https://github.com/actions/runner/issues/1182
    paths-ignore:
      - "public/**"
      - ".husky/**"
      - ".vscode/**"
      - "*.html"
      - ".nvmrc"
      - ".prettierignore"
      - ".prettierrc"
      - "Dockerfile"
      - "LICENSE"
      - "nginx.conf.template"
      - "README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "public/**"
      - ".husky/**"
      - ".vscode/**"
      - "*.html"
      - ".nvmrc"
      - ".prettierignore"
      - ".prettierrc"
      - "Dockerfile"
      - "LICENSE"
      - "nginx.conf.template"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-node_modules-

      - if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: npm run lint
      - run: npm run test -- --bail
      - run: npm run build:prod

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
