name: Bump NPM version and push git tag

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Type of version bump"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CONTENTS_WRITE_PAT }}

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: ".nvmrc"

      - run: |
          if [[ "${{ inputs.version_type }}" == "prerelease" || "${{ inputs.version_type }}" == "premajor" || "${{ inputs.version_type }}" == "preminor" || "${{ inputs.version_type }}" == "prepatch" ]]; then
            npm version ${{ inputs.version_type }} --preid alpha --no-git-tag-version
          else
            npm version ${{ inputs.version_type }} --no-git-tag-version
          fi
          git add package.json package-lock.json
          VERSION=$(node -p "require('./package.json').version")
          git commit -m "Bump version to $VERSION [skip ci]"
          git tag "v$VERSION"
          git push
          git push origin "v$VERSION"
