name: Build & test & push Docker image

on:
  workflow_call:
    inputs:
      dist-artifact-name:
        type: string
        required: true
      push:
        type: boolean
        required: false

env:
  TEST_TAG: digmaai/digma-ui:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.dist-artifact-name }}
      - run: |
          mkdir -p dist
          unzip -q ${{ inputs.dist-artifact-name }} -d dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}

      - name: Login to Docker Hub
        if: ${{ inputs.push == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DIGMAAI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DIGMAAI_TOKEN }}

      - name: Docker meta
        if: ${{ inputs.push == 'true' }}
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: digmaai/digma-ui
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=v(.*),group=1
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            # set latest tag for main branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push
        if: ${{ inputs.push == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
