name: Lint & test

on:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --bail
