name: Lint & test & build

on:
  push:
    branches:
      - "main"
    # Github Actions don't support YAML anchors yet, so we have to repeat
    # the paths-ignore in both push and pull_request events.
    # More info: https://github.com/actions/runner/issues/1182
    paths-ignore:
      - ".github/prompts/**"
      - ".husky/**"
      - ".vscode/**"
      - "website/**"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".github/prompts/**"
      - ".husky/**"
      - ".vscode/**"
      - "website/**"
      - "LICENSE"
      - "README.md"

jobs:
  lint-test:
    permissions:
      contents: read
    name: Lint & test
    uses: ./.github/workflows/lint-test.yml

  build-jetbrains:
    name: Build for JetBrains
    permissions:
      contents: read
      actions: write
    needs: lint-test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      platform: "jetbrains"

  build-vs:
    name: Build for Visual Studio
    permissions:
      contents: read
      actions: write
    needs: lint-test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      platform: "vs"

  build-web:
    name: Build for web
    permissions:
      contents: read
      actions: write
    needs: lint-test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      platform: "web"

  build-docker-image:
    name: Build Docker image
    permissions:
      contents: read
      actions: write
    needs: [build-jetbrains, build-vs, build-web]
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      dist-artifact-name: ${{ needs.build-web.outputs.artifact-name }}
      push: false
