name: Attach artifact to release

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true

permissions:
  contents: write

jobs:
  attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.artifact-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
