name: Lint & test & build & publish Docker image

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  lint-test:
    name: Lint & test
    uses: ./.github/workflows/lint-test.yml

  build-jetbrains:
    name: Build for JetBrains
    needs: lint-test
    uses: ./.github/workflows/build.yml
    with:
      platform: "jetbrains"

  attach-jetbrains-dist-asset:
    name: Attach JetBrains release asset
    needs: build-jetbrains
    uses: ./.github/workflows/attach-release-artifact.yml
    with:
      artifact-name: ${{ needs.build-jetbrains.outputs.dist-filename }}

  build-web:
    name: Build for web
    needs: lint-test
    uses: ./.github/workflows/build.yml
    with:
      platform: "web"

  attach-web-dist-asset:
    name: Attach web release asset
    needs: build-web
    uses: ./.github/workflows/attach-release-artifact.yml
    with:
      artifact-name: ${{ needs.build-web.outputs.dist-filename }}

  build-push-docker-image:
    name: Build & test & push Docker image
    needs: [build-jetbrains, build-web]
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dist-artifact-name: ${{ needs.build-web.outputs.dist-filename }}
      push: true
