name: Update dependencies

on:
  repository_dispatch:
    types: [update-dependencies]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: update-dependencies
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CONTENTS_WRITE_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Update dependencies.json
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > ./dependencies_diff.json
          npm run update-dependencies

      - name: Commit, push changes and create PR
        env:
          GH_TOKEN: ${{ secrets.CONTENTS_WRITE_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b ${{ env.BRANCH_NAME }}
          git add dependencies.json
          git commit -m "Update dependencies"
          git push origin ${{ env.BRANCH_NAME }}
          gh pr create -f -B main
